# Learning about Convolutions

Learning about convolutions step-by-step.

In [1]:
import torch
import torch.nn as nn

## 1D Convolutions

Lets start with a 3x4 tensor

In [2]:
x = torch.tensor([[1., -2., 3., -4.],
                  [1., -2., 3., -4.],
                  [1., -2., 3., -4.]])

In [3]:
x.shape

torch.Size([3, 4])

For `Conv1d()`, `in_channels` has to equal 3 since we have 3 rows

In [4]:
conv = torch.nn.Conv1d(in_channels = 3, out_channels = 3, kernel_size = 1)
conv(x)

tensor([[ 0.4199, -1.2442,  1.5293, -2.3536],
        [-1.6959,  1.9577, -4.1316,  4.3934],
        [ 1.0827, -1.3246,  2.6876, -2.9294]], grad_fn=<SqueezeBackward1>)

If we change the `out_channels` we control the number of rows of the output tensor

In [5]:
conv = torch.nn.Conv1d(in_channels = 3, out_channels = 1, kernel_size = 1)
conv(x)

tensor([[ 0.5089, -0.5794,  1.2343, -1.3048]], grad_fn=<SqueezeBackward1>)

Now let's change the input tensor just a little bit at `x[1,0]`

In [6]:
x = torch.tensor([[1., -2., 3., -4.],
                  [5., -2., 3., -4.],
                  [1., -2., 3., -4.]])

Now run the same `Conv1d()` over this tensor. 

(Note that we have not re-initialized the Conv1d function so it is the same Conv1d instance as above.)

In [7]:
conv(x)

tensor([[ 2.1653, -0.5794,  1.2343, -1.3048]], grad_fn=<SqueezeBackward1>)

Notice that only the first item of the output tensor has changed. So Conv1d processes the tensor "column-by-column" with an expectation of how many rows/dimensions are in each column based on value set to `in_channels`.


### Kernel Size Changed

But now let's run everything again with a different kernel size.

In [8]:
x = torch.tensor([[1., -2., 3., -4.],
                  [1., -2., 3., -4.],
                  [1., -2., 3., -4.]])

In [9]:
conv = torch.nn.Conv1d(in_channels = 3, out_channels = 1, kernel_size = 2)
conv(x)

tensor([[-0.6641, -0.0195, -0.7246]], grad_fn=<SqueezeBackward1>)

Note the size/shape of the output has changed from (1,4) to (1,3).

 1. The first item of the output is processed from the first and second columns of x
 2. Second item processed from second and third.
 3. Third item processed from third and fourth.

This is because the default `stride` value of `Conv1d()` is set equal to 1. `kernel_size` determines the size of the window that passes over the tensor. `stride` controls how the window passes over.

In [10]:
x = torch.tensor([[1., -2., 3., -4.],
                  [5., -2., 3., -4.],
                  [1., -2., 3., -4.]])

In [11]:
conv(x)

tensor([[ 0.4407, -0.0195, -0.7246]], grad_fn=<SqueezeBackward1>)

Again only the first value has changed. But now let's change numbers in the second column of x

In [12]:
x = torch.tensor([[1., -2., 3., -4.],
                  [1., 2.5, 3., -4.],
                  [1., -2., 3., -4.]])

In [13]:
conv(x)

tensor([[-0.6070,  1.2234, -0.7246]], grad_fn=<SqueezeBackward1>)

Now the first and second values are different. Since both the first and second values are dependent on values in the second column of x (i.e., the kernel for the first and second outputs both include the second column) this makes sense.

### Stride Changed

In [14]:
x = torch.tensor([[1., -2., 3., -4.],
                  [1., -2., 3., -4.],
                  [1., -2., 3., -4.]])

In [15]:
conv = torch.nn.Conv1d(in_channels = 3, out_channels = 1, kernel_size = 2, stride =2)
conv(x)

tensor([[0.4899, 0.6001]], grad_fn=<SqueezeBackward1>)

Notice that changing stride affects the size of the output.

In [16]:
x = torch.tensor([[1., -2., 3., -4.],
                  [1., 2.5, 3., -4.],
                  [1., -2., 3., -4.]])

In [17]:
conv(x)

tensor([[-0.0683,  0.6001]], grad_fn=<SqueezeBackward1>)

Now the first output value depends on x's first and second columns' values, and second output depends on x's third and fourth columns' values. So changing the second column's values only affects the first output value.

## 2D Convolutions

So wait a minute...a 1D convolution can still "handle" a 2-dimensional input or even higher. The "1D" in 1D convolutions doesn't refer to the the 1D size of the input, but the 1D size of the kernel.

Let's try everything again with `Conv2d`

In [18]:
# Notice the tensor is now 3D instead of 2D.
x = torch.tensor([[[1., -2., 3., -4.],
                  [1., -2., 3., -4.],
                  [1., -2., 3., -4.]]])

In [19]:
x.shape

torch.Size([1, 3, 4])

In [20]:
# NOTE: this won't work! in_channels has to equal 1, the first dimension of torch.Size. Think of this as a grayscale image. in_channels = 3 for RGB images. 
# conv = torch.nn.Conv2d(in_channels = 3, out_channels = 1, kernel_size = 2)

In [21]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 2)

In [22]:
conv(x)

tensor([[[-0.1720, -0.1394,  0.0036],
         [-0.1720, -0.1394,  0.0036]]], grad_fn=<SqueezeBackward1>)

In [23]:
conv(x).shape

torch.Size([1, 2, 3])

Now let's change `out_channels`

In [24]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 2, kernel_size = 2)

In [25]:
conv(x)

tensor([[[ 0.9437, -0.4663,  1.6787],
         [ 0.9437, -0.4663,  1.6787]],

        [[-0.1756,  0.4394, -0.5947],
         [-0.1756,  0.4394, -0.5947]]], grad_fn=<SqueezeBackward1>)

### Kernel Size Change

In [26]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = (2,3))

In [27]:
conv(x)

tensor([[[ 1.5348, -1.9661],
         [ 1.5348, -1.9661]]], grad_fn=<SqueezeBackward1>)

In [28]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = (3,3))

In [29]:
conv(x)

tensor([[[-1.2753,  2.1745]]], grad_fn=<SqueezeBackward1>)

At the risk of confusing things, you can say that a Conv1D for a 2D tensor of size (R,C) with `kernel_size` = X is the same as a Conv2D where `kernel_size` = (R,X) for a 3D tensor of size (1, R, C) for any value of X

### Stride Changed

In [30]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = (3,3), stride=2)

In [31]:
conv(x)

tensor([[[0.2969]]], grad_fn=<SqueezeBackward1>)

Notice that when the kernel "window goes outside the tensor" it doesn't break, but just doesn't return any values

In [32]:
# Notice the tensor is now 3D instead of 2D.
x = torch.tensor([[[1., -2., 3.],
                  [1., -2., 3.],
                  [1., -2., 3.]]])

In [33]:
conv(x)

tensor([[[0.2969]]], grad_fn=<SqueezeBackward1>)

Given the (3,3) kernel, this means that the fourth column's values essentially don't matter to the output of the 2D convolution

### Padding Changed

Start with original tensor and a (3,3) kernel convolution

In [34]:
# Notice the tensor is now 3D instead of 2D.
x = torch.tensor([[[1., -2., 3., -4.],
                  [1., -2., 3., -4.],
                  [1., -2., 3., -4.]]])

In [37]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 3)

In [38]:
conv(x)

tensor([[[ 1.2265, -1.7543]]], grad_fn=<SqueezeBackward1>)

Change padding from 0 to 1. This adds 1 extra cell on the "border" of the tensor. Each cell is filled with value of 0 (`padding_mode='zeros'`)

In [41]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 3, padding=1)

In [42]:
conv(x)

tensor([[[ 0.8060, -1.3511,  2.4074, -1.7916],
         [ 0.7081, -1.2467,  2.2964, -1.6546],
         [ 0.2024, -0.0433,  0.3955,  0.4569]]], grad_fn=<SqueezeBackward1>)

### Dilation

Start with original tensor and a (2,2) kernel convolution

NOTE: Default `dilation=1` not 0!!!!

In [45]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 2)

In [46]:
conv(x)

tensor([[[ 0.0578, -0.6624, -0.0847],
         [ 0.0578, -0.6624, -0.0847]]], grad_fn=<SqueezeBackward1>)

In [49]:
conv = torch.nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 2, dilation=2)

In [50]:
conv(x)

tensor([[[-1.3338,  0.9549]]], grad_fn=<SqueezeBackward1>)

See "Dilated convolution animations" in https://github.com/vdumoulin/conv_arithmetic/blob/master/README.md for visualization of dilations